### ISSUE TITLE
possible error..

### ISSUE THREAD

**Issue by jahman07104** [learn-co-curriculum/programming-univbasics-working-with-string#2]
Identify why TypeError Happens When + String with Integer
fact = "Byron is "
tail = " years old"
age = 5
 
fact + age + tail #=> TypeError (no implicit conversion of Integer into String)
Ruby is not sure whether you want to add like an Integer (stored in tail) or add like Strings! If you need to do this, you should use the to_s method on data.

I think the integer is stored in AGE and not in Tail per the text..

**Comment by maxwellbenton** [comment]
Hi @jahman07104,

Absolutely correct. Thank you for spotting this and providing feedback. We've fixed this error so that it correctly states that the Integer is stored in `age`.

Thank you for contributing to a Learn lesson!
