### ISSUE TITLE
example missing the +

### ISSUE THREAD

**Issue by matthewvaneck84** [learn-co-curriculum/programming-univbasics-working-with-string#3]
Join Strings using +
Now here's an interesting use of the + operator when placed between Strings, it joins them and returns a new String.

first_name = "Byronius"
clan_name = "Karbitus"
common_name = "Maris"
 
# With +
first_name + " " + clan_name + " " common_name #=> "Byronius Karbitus Maris"
 
# Or, with interpolation, like you already know
"#{first_name} #{clan_name} #{common_name}" #=> "Byronius Karbitus Maris"

Hello,
The example above for # With + is missing the + between " " and common_name. I kept getting an error until I added it myself.

Thank you,
Matthew Van Eck

**Comment by sgharms** [comment]
Thanks! And fixed!
